version: '3'


services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    #volumes:
      #- ./dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    #volumes:
      #- ./requirements/tools/wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/tools/wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:

networks:
  app-network:
    driver: bridge
