version: '3'


services:

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ./tools/wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tools/wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:

networks:
  app-network:
    driver: bridge
